services:
  - type: worker
    name: kino-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: kino_bot
      - key: ADMIN_IDS
        sync: false
      - key: PAYMENTS_CHAT_ID
        sync: false
      - key: SUPPORT_USERNAME
        value: "@x7fan"
      - key: CARD_NUMBER
        sync: false
      - key: CARD_OWNER
        sync: false
      - key: DEV_USERNAME
        value: "@x7fan"
